server:
  port: ${SERVER_PORT:18080}
  address: 127.0.0.1
spring:
  application:
    name: qlbh
  datasource:
#     Ví dụ H2 file để dễ di chuyển
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlite:${user.home}/.qlbh/database.db}
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    open-in-view: true
  hikari:
    maximum-pool-size: 1
    minimum-idle: 1
    pool-name: sqlite-pool

#  datasource:
#      url: jdbc:postgresql://localhost:5432/QLBH_BD2
#      username: postgres
#      password: 123456
#      driver-class-name: org.postgresql.Driver
#
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate.format_sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
neon:
  datasource:
    url: ${NEON_DB_URL:jdbc:postgresql://ep-blue-snow-adnaddk9-pooler.c-2.us-east-1.aws.neon.tech:5432/neondb?sslmode=require}
    username: ${NEON_DB_USER:neondb_owner}
    password: ${NEON_DB_PASSWORD:npg_IjmbzsS7Yyp0}
    maximum-pool-size: ${NEON_MAX_POOL_SIZE:5}

management:
  endpoints.web.exposure.include: health,info

jwt:
  secret: BxsmVbElz3wP7iqRPIxnLSCuc1xJ890ymIPrvtkheXny6NZtiaWzIHOefrBoKIp5
  expiration-ms: ${JWT_EXPIRATION_MS:8760}
